version: "3"
services:
  crypto_bitcoin_mainnet:
    container_name: solidarity_crypto_bitcoin_mainnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -chain=main
      -server
      -printtoconsole=1
      -maxuploadtarget=5000
      -txindex=1
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcport=8333
      -rpcuser=solidarity
      -rpcpassword=\${CRYPTO_PASSWORD}
      -dbcache=1024
    ports:
      - "8333:8333"
    volumes:
      - ~/bitcoin-mainnet:/home/bitcoin/.bitcoin

  crypto_bitcoin_testnet:
    container_name: solidarity_crypto_bitcoin_testnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -chain=test
      -server
      -printtoconsole=1
      -maxuploadtarget=5000
      -txindex=1
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcport=18333
      -rpcuser=solidarity
      -rpcpassword=\${CRYPTO_PASSWORD}
      -dbcache=1024
    ports:
      - "18333:18333"
    volumes:
      - ~/bitcoin-testnet:/home/bitcoin/.bitcoin

  database:
    container_name: solidarity_database
    image: mcr.microsoft.com/mssql/server
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=\${DATABASE_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - "~/solidarity-database:/var/opt/mssql"

  server:
    container_name: solidarity_server
    image: solidarity_server:latest
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_SERVER=solidarity_database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=\${DATABASE_PASSWORD}
      - JWT_KEY=\${JWT_KEY}
      - PAYMENT_METHODS=BTC_MAINNET
      - PAYMENT_METHOD_BTC_MAINNET_SERVER=http://solidarity_crypto_bitcoin_mainnet:8333/
      - PAYMENT_METHOD_BTC_MAINNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_MAINNET_PASSWORD=\${CRYPTO_PASSWORD}
      - PAYMENT_METHOD_BTC_TESTNET_SERVER=http://solidarity_crypto_bitcoin_testnet:18333/
      - PAYMENT_METHOD_BTC_TESTNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_TESTNET_PASSWORD=\${CRYPTO_PASSWORD}

  client:
    container_name: solidarity_client
    image: solidarity_client:latest
    restart: always
    ports:
      - "80:80"