version: "3"
services:
  crypto_bitcoin_mainnet:
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -chain=main
      -server
      -printtoconsole=1
      -maxuploadtarget=5000
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcport=8333
      -rpcuser=solidarity
      -rpcpassword=${CRYPTO_PASSWORD}
      -dbcache=1024
    volumes:
      - ~/bitcoin:/home/bitcoin/.bitcoin

  database:
    image: mcr.microsoft.com/mssql/server
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - "~/solidarity/prod/database:/var/opt/mssql"

  server:
    image: solidarity_server:latest
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_SERVER=database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - PAYMENT_METHODS=BTC_MAINNET
      - PAYMENT_METHOD_BTC_MAINNET_SERVER=http://crypto_bitcoin_mainnet:8333/
      - PAYMENT_METHOD_BTC_MAINNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_MAINNET_PASSWORD=${CRYPTO_PASSWORD}

  client:
    image: solidarity_client:latest
    restart: always
    ports:
      - "80:80"