version: "3"
services:
  sqlserver:
    container_name: solidarity_database
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DevPa$$w0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
  server:
    container_name: solidarity_server
    build:
      context: ./packages/Server
    ports: 
      - "5000:80"
    volumes:
      - "./packages/Server:/Solidarity"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_SERVER=solidarity_database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=DevPa$$w0rd
      - JWT_KEY=75pQjmReLS7FRTYZg7ehvb2NE5ZtEkdMdw7h7CKgLh4S8T45jUS9jbuUqLeeUdcP
      # TODO: Crypto Note conainers
      - CRYPTONODES_BITCOIN_MAINNET_SERVER=http://0.0.0.0:8000/
      - CRYPTONODES_BITCOIN_MAINNET_USERNAME=bitcoin
      - CRYPTONODES_BITCOIN_MAINNET_PASSWORD=xxxxxxxxxxxxxx
      - CRYPTONODES_BITCOIN_TESTNET_SERVER=http://0.0.0.0:8001/
      - CRYPTONODES_BITCOIN_TESTNET_USERNAME=bitcoin
      - CRYPTONODES_BITCOIN_TESTNET_PASSWORD=xxxxxxxxxxxxxx
  client:
    container_name: solidarity_client
    build:
      context: ./packages/Client
    ports:
      - "8080:8080"
    volumes:
      - "./packages/Client:/Solidarity"