version: "3"
services:
  database:
    container_name: solidarity_database
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev_Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  server:
    container_name: solidarity_server
    restart: always
    build:
      context: ./packages/Server
    ports: 
      - "5000:80"
    volumes:
      - "./packages/Server:/Solidarity"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - DATABASE_SERVER=solidarity_database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=Dev_Passw0rd
      - JWT_KEY=75pQjmReLS7FRTYZg7ehvb2NE5ZtEkdMdw7h7CKgLh4S8T45jUS9jbuUqLeeUdcP
      # TODO: activated payment methods
      - PAYMENT_METHODS=BTC_MAINNET,BTC_TESTNET
      # TODO: Crypto Node conainers
      - PAYMENT_METHOD_BTC_MAINNET_SERVER=http://0.0.0.0:8000/
      - PAYMENT_METHOD_BTC_MAINNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_MAINNET_PASSWORD=xxxxxxxxxxxxxx
      - PAYMENT_METHOD_BTC_TESTNET_SERVER=http://0.0.0.0:8001/
      - PAYMENT_METHOD_BTC_TESTNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_TESTNET_PASSWORD=xxxxxxxxxxxxxx

  client:
    container_name: solidarity_client
    restart: always
    build:
      context: ./packages/Client
    ports:
      - "8080:8080"
    volumes:
      - "./packages/Client:/Solidarity"