version: "3"
services:
  crypto_bitcoin_mainnet:
    container_name: solidarity_crypto_bitcoin_mainnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -chain=main
      -server
      -printtoconsole=1
      -maxuploadtarget=5000
      -txindex=0
      -prune=10000
      -dbcache=1024
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcport=8333
      -rpcuser=solidarity
      -rpcpassword=Dev_Passw0rd
    ports:
      - "8333:8333"
    volumes:
      - ~/solidarity/bitcoin-mainnet:/home/bitcoin/.bitcoin

  crypto_bitcoin_testnet:
    container_name: solidarity_crypto_bitcoin_testnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -chain=test
      -server
      -printtoconsole=1
      -maxuploadtarget=5000
      -txindex=0
      -prune=10000
      -dbcache=1024
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcport=18333
      -rpcuser=solidarity
      -rpcpassword=Dev_Passw0rd
    ports:
      - "18333:18333"
    volumes:
      - ~/solidarity/bitcoin-testnet:/home/bitcoin/.bitcoin

  database:
    container_name: solidarity_database
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev_Passw0rd
      - MSSQL_SA_PASSWORD=Dev_Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    # volumes:
      # - "~/solidarity/database:/var/opt/mssql"

  server:
    container_name: solidarity_server
    restart: always
    depends_on:
      - solidarity_database
    build:
      context: ./packages/Server
    ports: 
      - "5000:80"
    volumes:
      - "./packages/Server:/Solidarity"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - DATABASE_SERVER=solidarity_database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=Dev_Passw0rd
      - JWT_KEY=75pQjmReLS7FRTYZg7ehvb2NE5ZtEkdMdw7h7CKgLh4S8T45jUS9jbuUqLeeUdcP
      - PAYMENT_METHODS=BTC_TESTNET
      - PAYMENT_METHOD_BTC_MAINNET_SERVER=http://solidarity_crypto_bitcoin_mainnet:8333/
      - PAYMENT_METHOD_BTC_MAINNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_MAINNET_PASSWORD=Dev_Passw0rd
      - PAYMENT_METHOD_BTC_TESTNET_SERVER=http://solidarity_crypto_bitcoin_testnet:18333/
      - PAYMENT_METHOD_BTC_TESTNET_USERNAME=solidarity
      - PAYMENT_METHOD_BTC_TESTNET_PASSWORD=Dev_Passw0rd

  client:
    container_name: solidarity_client
    restart: always
    depends_on:
      - solidarity_server
    build:
      context: ./packages/Client
    ports:
      - "8080:8080"
    volumes:
      - "./packages/Client:/Solidarity"