version: "3"
services:
  crypto_bitcoin_mainnet:
    container_name: solidarity_crypto_bitcoin_mainnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -testnet=0
      -server=1
      -rpcuser=solidarity
      -rpcpassword=\${CRYPTO_PASSWORD}
      -rpcallowip=::/0
      -rpcport=8332
      -printtoconsole=1
      -maxconnections=8
      -maxuploadtarget=144
      -disablewallet=0
      -txindex=0
      -prune=10000
      -dbcache=1024
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -zmqpubhashtx=tcp://0.0.0.0:28333
      -zmqpubhashblock=tcp://0.0.0.0:28333
    ports:
      - "8332:8332"
    volumes:
      - ~/bitcoin-mainnet:/home/bitcoin/.bitcoin

  crypto_bitcoin_testnet:
    container_name: solidarity_crypto_bitcoin_testnet
    image: ruimarinho/bitcoin-core
    restart: always
    command:
      -testnet=1
      -server=1
      -rpcuser=solidarity
      -rpcpassword=\${CRYPTO_PASSWORD}
      -rpcallowip=::/0
      -rpcport=18332
      -printtoconsole=1
      -maxconnections=8
      -maxuploadtarget=144
      -disablewallet=0
      -txindex=0
      -prune=10000
      -dbcache=1024
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -zmqpubhashtx=tcp://0.0.0.0:28333
      -zmqpubhashblock=tcp://0.0.0.0:28333
    ports:
      - "18332:18332"
    volumes:
      - ~/bitcoin-testnet:/home/bitcoin/.bitcoin

  database:
    container_name: solidarity_database
    image: mcr.microsoft.com/mssql/server
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=\${DATABASE_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - "~/solidarity-database:/var/opt/mssql"

  server:
    container_name: solidarity_server
    image: solidarity_server:latest
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_SERVER=solidarity_database,1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=\${DATABASE_PASSWORD}
      - JWT_KEY=\${JWT_KEY}
      - CRYPTO_BITCOIN_MAINNET_SERVER=solidarity_crypto_bitcoin_mainnet
      - CRYPTO_BITCOIN_MAINNET_USERNAME=solidarity
      - CRYPTO_BITCOIN_MAINNET_PASSWORD=\${CRYPTO_PASSWORD}
      - CRYPTO_BITCOIN_TESTNET_SERVER=solidarity_crypto_bitcoin_testnet
      - CRYPTO_BITCOIN_TESTNET_USERNAME=solidarity
      - CRYPTO_BITCOIN_TESTNET_PASSWORD=\${CRYPTO_PASSWORD}

  client:
    container_name: solidarity_client
    image: solidarity_client:latest
    restart: always
    ports:
      - "80:80"