global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.IdentityModel.Tokens;
global using NBitcoin;
global using NBitcoin.RPC;
global using NetTopologySuite.Geometries;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Solidarity;
global using Solidarity.Application.Abstractions;
global using Solidarity.Application.Accounts;
global using Solidarity.Application.Authentication;
global using Solidarity.Application.Campaigns;
global using Solidarity.Application.Files;
global using Solidarity.Application.PaymentMethods;
global using Solidarity.Domain.Models;
global using Solidarity.Infrastructure;
global using Solidarity.Infrastructure.Identity;
global using Solidarity.Infrastructure.Persistence;
global using Solidarity.Infrastructure.Payment;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Net;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Reflection;
global using Xunit;
global using System.Text.RegularExpressions;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using TanvirArjel.Extensions.Microsoft.DependencyInjection;

WebApplication.CreateBuilder(args)
	.InstallSolidarity().Build()
	.ConfigureSolidarity().Run();