name: Development Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - issue2-infra-deployment-via-docker-compose

jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build server image
        run: docker build -f ./packages/Server/Dockerfile.prod --tag solidarity_server:latest ./packages/Server

      - name: Save server image
        run: docker save solidarity_server:latest -o solidarity_server_image

      - name: Upload server image to GitHub
        uses: actions/upload-artifact@v2
        with:
          path: solidarity_server_image
          name: solidarity_server_image

  Client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build client image
        run: docker build -f ./packages/Client/Dockerfile.prod --tag solidarity_client:latest ./packages/Client

      - name: Save client image
        run: docker save solidarity_client:latest -o solidarity_client_image

      - name: Upload client image to GitHub
        uses: actions/upload-artifact@v2
        with:
          path: solidarity_client_image
          name: solidarity_client_image

  Deploy:
   runs-on: ubuntu-latest
   needs:
     - Server
     - Client
   steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Download server image file from GitHub
        uses: actions/download-artifact@v2
        with:
          name: solidarity_server_image

      - name: Download client image file from GitHub
        uses: actions/download-artifact@v2
        with:
          name: solidarity_client_image

      - name: Upload images and compose file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "solidarity_server_image,solidarity_client_image,docker-compose.prod.yml"
          target: "~"
          overwrite: true
        
      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: docker-compose -f ./docker-compose.prod.yml down && docker load -i ./solidarity_server_image && docker load -i ./solidarity_client_image && docker-compose -f ./docker-compose.prod.yml up -d