name: Development Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Build Server Image
        run: docker build ./packages/Server -f Dockerfile.prod --tag solidarity_server:latest

      - name: Save Server Image
        run: docker save solidarity_server:latest -o solidarity_server_image

      - name: Upload Server Image to GitHub
        uses: actions/upload-artifact@v1.0.0
        with:
          name: solidarity_server_image
          path: solidarity_server_image

      - name: Upload Docker Compose File to GitHub
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-compose.prod.yml
          path: docker-compose.yml

  Client:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Build Client Image
        run: docker build ./packages/Client -f Dockerfile.prod --tag solidarity_client:latest

      - name: Save Client Image
        run: docker save solidarity_client:latest -o solidarity_client_image

      - name: Upload Client Image to GitHub
        uses: actions/upload-artifact@v1.0.0
        with:
          name: solidarity_client_image
          path: solidarity_client_image

  Deploy:
   runs-on: ubuntu-latest
   needs:
     - Server
     - Client
   steps:
      - name: Download Server Image from GitHub
        uses: actions/download-artifact@v1.0.0
        with:
          name: solidarity_server_image
          path: solidarity_server_image

      - name: Download Client Image from GitHub
        uses: actions/download-artifact@v1.0.0
        with:
          name: solidarity_client_image
          path: solidarity_client_image

      - name: Download Docker Compose File from GitHub
        uses: actions/download-artifact@v1.0.0
        with:
          name: docker-compose.yml
          path: docker-compose.yml

      - name: Upload Images and Compose File to the Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "solidarity_server_image,solidarity_client_image,docker-compose.yml"
          target: "~"
          overwrite: true
        
      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: docker load -i .\solidarity_server_image && docker load -i .\solidarity_client_image && docker-compose up -d